scr_npc_list_add_dialog(questions_map, "tailor_backpack_pc", "map")
scr_npc_list_add_dialog(questions_map, "tailor_backpack_inquiry", "map")
scr_npc_list_add_dialog(questions_map, "tailor_backpack_inquiry_pc", "map")
scr_npc_list_add_dialog(questions_map, "tailor_backpack_quest", "map")
scr_npc_list_add_dialog(questions_map, "backpack_materials_collected", "map")
scr_npc_list_add_dialog(questions_map, "tailor_making_backpack", "map")